#!/bin/bash
# Cron Job Setup Script for Post-Game Analysis System
# 
# This script sets up the cron jobs for automated projection collection and analysis
# 
# WARNING: This will add cron jobs to your system. Review the jobs before enabling.
# 
# To enable cron jobs:
# 1. Update the paths in the cron job definitions below
# 2. Run this script: ./scripts/automation/setup_cron_jobs.sh
# 3. Verify with: crontab -l
# 
# To disable cron jobs:
# 1. Run: crontab -e
# 2. Comment out or delete the fantasy football cron jobs

# Get the current directory (project root)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

echo "Setting up cron jobs for Fantasy Football Post-Game Analysis System"
echo "Project root: $PROJECT_ROOT"
echo ""

# Check if crontab exists
if ! crontab -l >/dev/null 2>&1; then
    echo "No existing crontab found. Creating new one."
    crontab -l > /dev/null 2>&1 || true
fi

# Create temporary crontab file
TEMP_CRON=$(mktemp)

# Get existing crontab (if any)
crontab -l > "$TEMP_CRON" 2>/dev/null || true

# Add comment header
echo "" >> "$TEMP_CRON"
echo "# Fantasy Football Post-Game Analysis System" >> "$TEMP_CRON"
echo "# Generated by setup_cron_jobs.sh on $(date)" >> "$TEMP_CRON"
echo "" >> "$TEMP_CRON"

# Add cron jobs (commented out for safety)
echo "# Thursday 2:00 PM - Collect Thursday projections" >> "$TEMP_CRON"
echo "# 0 14 * * 4 cd $PROJECT_ROOT && ./scripts/automation/collect_thursday_projections.sh" >> "$TEMP_CRON"
echo "" >> "$TEMP_CRON"

echo "# Sunday 8:00 AM - Collect Sunday projections" >> "$TEMP_CRON"
echo "# 0 8 * * 0 cd $PROJECT_ROOT && ./scripts/automation/collect_sunday_projections.sh" >> "$TEMP_CRON"
echo "" >> "$TEMP_CRON"

echo "# Monday 2:00 PM - Collect Monday projections" >> "$TEMP_CRON"
echo "# 0 14 * * 1 cd $PROJECT_ROOT && ./scripts/automation/collect_monday_projections.sh" >> "$TEMP_CRON"
echo "" >> "$TEMP_CRON"

echo "# Tuesday 9:00 AM - Run post-game analysis" >> "$TEMP_CRON"
echo "# 0 9 * * 2 cd $PROJECT_ROOT && ./scripts/automation/run_post_game_analysis.sh" >> "$TEMP_CRON"
echo "" >> "$TEMP_CRON"

# Install the crontab
crontab "$TEMP_CRON"

# Clean up
rm "$TEMP_CRON"

echo "Cron jobs have been added (commented out for safety)"
echo ""
echo "To enable the cron jobs:"
echo "1. Run: crontab -e"
echo "2. Uncomment the lines you want to enable"
echo "3. Save and exit"
echo ""
echo "To view current cron jobs:"
echo "crontab -l"
echo ""
echo "To remove all fantasy football cron jobs:"
echo "crontab -e"
echo "Then delete or comment out the Fantasy Football section"
